<!DOCTYPE html>
<html>
<head>
    <title>Вход для администрации</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css">   
</head>
<body>
    <?php drawNavBar() ?>
    <div class="main form" >
        <form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
            <input type="hidden" name="csrf_token" value="<?php echo getToken() ?>">
            <div class="field">
                <label for="login">Введите логин</label>
                <input type="text" class="inp" name="login" id="login" value="<?= htmlspecialchars($login, ENT_QUOTES) ?>">
            </div>
            <?php if ( !empty($error) ) { ?>
            <div class="error">
                <span class="label label-important">Неверный логин <br> или пароль!</span>
            </div>
            <?php } ?>
            <div class="field">
                <label for="password">Введите пароль</label>
                <input type="password" class="inp" name="password" id="password">
            </div>
            <div class="field">
            <input type="submit" value="Войти" name="submit" class="btn btn-info login">
            </div>
        </form>
    </div>
</body>
</html>
