<?php
session_start();
require 'nav-menu.php';
require 'config.php'; 
drawNavBar();
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Успех!</title>
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
    <h3>Спасибо! Ваша жалоба отправлена. Мы внимательно ее изучим, и в случае необходимости, свяжемся с вами.</h3>
    Хотите вернуться на <a href="index.php">главную страницу?</a>
</body>
</html>
