<!DOCTYPE html>
<html>
<head>
    <title>Успешая регистрация</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css">
</head>
<body>
    <?php require 'nav-menu.php' ?>
    <?php drawNavBar() ?>
    <h3 class="success-registr">Вы успешно зарегистировались. Теперь вы можете <a href="login.php">войти в систему</a> через свой логин и пароль.</h3>
</body>
</html>
